[tool.poetry]
name = "magos"
version = "0.1.0"
description = ""
authors = ["BLooperZ <blooperz@users.noreply.github.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
typing-extensions = "^4.3.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pyinstaller = "^5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
